nanoGPT
========
Following a tutorial from [Andrej Karpathy](https://karpathy.ai/):
- [Let's build GPT: from scratch, in code, spelled out.](https://youtu.be/kCc8FmEb1nY?list=PLAqhIrjkxbuWI23v9cThsA9GvCAUhRvKZ)

## Setup

In [17]:
# download the dataset file from github
# !wget https://github.com/karpathy/char-rnn/raw/master/data/tinyshakespeare/input.txt

In [18]:
import torch
import torch.nn as nn
import torch.nn.functional as F
# import matplotlib.pyplot as plt
# %matplotlib inline

In [47]:
# hyperparameters
batch_size = 32
block_size = 8
max_iters = 5000
eval_interval = 300
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
# device = 'cpu'
eval_iters = 200
n_embd = 32

In [20]:
# read in all the text
text = open('input.txt', 'r', encoding='utf-8').read()
print(f'{len(text)=}\n---\n{text[:100]}')

len(text)=1115394
---
First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You


In [21]:
chars = sorted(set(text))
vocab_size = len(chars)
print(''.join(chars), vocab_size)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz 65


In [22]:
# encode the input into a computer friendly format
# here we are tokenizing character by character, in real life chatGPT uses a byte-pair encoding (BPE),
# it's a sub-word units, which means they don't use entire words as token, only chunks of binary

# in real life we'd use something like
# import tiktoken
# enc = tiktoken.get_encoding('gpt2')
# enc.encode('I for one welcome our new AI overlords')
# enc.decode([40, 329, 530, 7062, 674, 649, 9552, 12893, 3669])

# for our toy example we use some manual encoding
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for i, ch in enumerate(chars)}
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])

# we have a good candidate for quickcheck-style auto generated tests here
s = 'string generated by quickcheck from our vocab'
assert s == decode(encode(s)), f'{s} did not encore/decode correctly'

print(encode('I for one welcome our new AI overlords'))
print(decode([21, 1, 44, 53, 56, 1, 53, 52, 43, 1, 61, 43, 50, 41, 53, 51, 43, 1, 53, 59, 56, 1, 52, 43, 61, 1, 13, 21, 1, 53, 60, 43, 56, 50, 53, 56, 42, 57]))

[21, 1, 44, 53, 56, 1, 53, 52, 43, 1, 61, 43, 50, 41, 53, 51, 43, 1, 53, 59, 56, 1, 52, 43, 61, 1, 13, 21, 1, 53, 60, 43, 56, 50, 53, 56, 42, 57]
I for one welcome our new AI overlords


In [23]:
# encode the dataset
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:100])

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59])


In [24]:
# split the data into training set and validation set
n = int(0.9 * len(data))
train_data = data[:n]
val_data = data[n:]

In [25]:
# chunk the dataset into smaller pieces for training
# in practice we will train in all sizes < chunk
# e.g. for a chunk size of 8 we will train on chunks of size 1 to 8

def get_batch(dataset):
    data = train_data if dataset == 'train' else val_data
    ix = torch.randint(len(data) - block_size - 1, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

xb, yb = get_batch('train')
print(xb[:2])
print(yb[:2])

tensor([[ 1, 46, 53, 54, 43,  1, 47, 52],
        [23, 17,  1, 34, 21, 26, 15, 17]], device='cuda:0')
tensor([[46, 53, 54, 43,  1, 47, 52,  5],
        [17,  1, 34, 21, 26, 15, 17, 26]], device='cuda:0')


In [26]:
@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

## Implem: Bigram Model

In [48]:
# B: [B]atch size (batch_size)
# T: [T]okens sequence length (block_size)
# C: [C]hannel is the embeddings size (n_embd)
#torch.manual_seed(1337) # for reproducibility

class Head(nn.Module):
    def __init__(self, head_size):
        super().__init__()
        self.head_size = head_size
        self.key = nn.Linear(C, head_size, bias=False)
        self.query = nn.Linear(C, head_size, bias=False)
        self.value = nn.Linear(C, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

    def forward(self, x):
        B, T, C = x.shape
        k = self.key(x)
        q = self.query(x)
        # compute attention scores (affinities)
        wei = q @ k.transpose(-2, -1) * self.head_size**-0.5
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf'))
        wei = F.softmax(wei, dim=-1)
        v = self.value(x)
        out = wei @ v
        return out

class BigramLanguageModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.sa_head = Head(n_embd)
        self.lm_head = nn.Linear(n_embd, vocab_size)
        
    def forward(self, idx, targets=None):
        B, T = idx.shape
        # idx and targets are (B, T)
        tok_emb = self.token_embedding_table(idx) # (B, T, C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T, C)
        x = tok_emb + pos_emb # (B, T, C)
        x = self.sa_head(x) # apply one head of self-attention
        logits = self.lm_head(x) # (B, T, vocab_size)

        if targets is None:
            loss = None
        else:
            # juggle with tensor shapes to match pytorch's cross_entropy
            B, T, C = logits.shape
            logits = logits.view(B * T, C)
            targets = targets.view(B * T)
            loss = F.cross_entropy(logits, targets)
        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        for _ in range(max_new_tokens):
            # crop the context to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            logits, loss = self(idx_cond)
            logits = logits[:, -1, :]
            probs = F.softmax(logits, dim=-1)
            idx_next = torch.multinomial(probs, num_samples=1)
            idx = torch.cat((idx, idx_next), dim=1)
        return idx
    
model = BigramLanguageModel()
m = model.to(device)
logits, loss = m(xb, yb)
print(logits.shape)
# Note: by default we have a vocab of size 65, so before training we expect a loss of: -ln(1/65) = 4.17
print(loss.item())

torch.Size([256, 65])
4.249378204345703


In [49]:
# create a pytorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

In [50]:
# train
for iter in range(max_iters):
    if iter % eval_interval == 0:
        losses = estimate_loss()
        print(f'step {iter}: train loss {losses["train"]:.4f}, val loss {losses["val"]:.4f}')

    xb, yb = get_batch('train')
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

step 0: train loss 4.2538, val loss 4.2487
step 300: train loss 3.0264, val loss 3.0483
step 600: train loss 2.7055, val loss 2.7007
step 900: train loss 2.5799, val loss 2.5758
step 1200: train loss 2.5173, val loss 2.5184
step 1500: train loss 2.4721, val loss 2.4849
step 1800: train loss 2.4535, val loss 2.4581
step 2100: train loss 2.4399, val loss 2.4489
step 2400: train loss 2.4284, val loss 2.4409
step 2700: train loss 2.4124, val loss 2.4325
step 3000: train loss 2.4187, val loss 2.4165
step 3300: train loss 2.4078, val loss 2.4143
step 3600: train loss 2.3968, val loss 2.4132
step 3900: train loss 2.3978, val loss 2.4143
step 4200: train loss 2.3947, val loss 2.4050
step 4500: train loss 2.3987, val loss 2.4040
step 4800: train loss 2.3913, val loss 2.3934


In [51]:
# sample from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=100)[0].tolist()))


And thef bridcowf, har on, ber

Hiset bobe toe.
SGBO:
IS:
Falilanss:
Want he usqouthe. bar dthas ate


## understand self-attention

In [34]:
torch.manual_seed(1337) # for reproducibility
B, T, C = 4, 8, 32
x = torch.randn(B, T, C)
x.shape

torch.Size([4, 8, 32])

In [35]:
# we want to compute x[b, t] = mean_{i<=t} x[b, i]

# naive implementation
# x_bag_of_word
xbow = torch.zeros((B, T, C))
for b in range(B):
    for t in range(T):
        xprev = x[b, :t + 1]
        xbow[b, t] = torch.mean(xprev, dim=0)

# vectorized implementation
a = torch.tril(torch.ones(T, T))
a = a / torch.sum(a, dim=1, keepdim=True)
xbow2 = a @ x
print(f'a = \n{a}')
print(xbow[0])
print(xbow2[0])

# vectorized implementation using softmax
tril = torch.tril(torch.ones(T, T))
a = torch.zeros((T, T))
a = a.masked_fill(tril == 0, float('-inf'))
a = F.softmax(a, dim=1)
xbow3 = a @ x
torch.allclose(xbow2, xbow3)

a = 
tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])
tensor([[ 1.8077e-01, -6.9988e-02, -3.5962e-01, -9.1520e-01,  6.2577e-01,
          2.5510e-02,  9.5451e-01,  6.4349e-02,  3.6115e-01,  1.1679e+00,
         -1.3499e+00, -5.1018e-01,  2.3596e-01, -2.3978e-01, -9.2111e-01,
          1.5433e+00,  1.3488e+00, -1.3964e-01,  2.8580e-01,  9.6512e-01,
         -2.0371e+00,  4.9314e-01,  1.4870e+00,  5.9103e-01,  1.2603e-01,
         -1.5627e+00, -1.1601e+0

True

In [40]:
# self-attention
# implement a single head of self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, head_size)
q = query(x) # (B, T, head_size)
wei = q @ k.transpose(-2, -1) # (B, T, head_size) @ (B, head_size, T) -> (B, T, T)
wei *= head_size**-0.5 # scale the weights

tril = torch.tril(torch.ones(T, T))
# mask the future tokens embeddings because we are on a decoder block and we don't know words in the future.
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=1)

v = value(x) # (B, T, head_size)
out = wei @ v

In the "attention is all you need" paper the scaled dot-product attention is:

$Attention(Q,K,V)=softmax({Q K^{T} \over {\sqrt d_{k}}}) V$
